version: 2
project_name: tempo-cli

builds:
  - main: ./main.go
    binary: tempo-cli
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

brews:
  - repository:
      owner: usetempo
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: https://github.com/usetempo/tempo-cli
    description: AI code attribution for git commits
    install: |
      bin.install "tempo-cli"
