package detector

import (
	"testing"
)

func TestDetectTrailers_ClaudeCode(t *testing.T) {
	msg := "Fix auth bug\n\nCo-Authored-By: Claude <noreply@anthropic.com>"
	dets := detectTrailers(msg)
	if len(dets) != 1 {
		t.Fatalf("expected 1 detection, got %d", len(dets))
	}
	if dets[0].Tool != ToolClaudeCode {
		t.Errorf("tool: got %q, want %q", dets[0].Tool, ToolClaudeCode)
	}
	if dets[0].Method != MethodCoAuthorTrailer {
		t.Errorf("method: got %q, want %q", dets[0].Method, MethodCoAuthorTrailer)
	}
	if dets[0].Confidence != ConfidenceMedium {
		t.Errorf("confidence: got %q, want %q", dets[0].Confidence, ConfidenceMedium)
	}
}

func TestDetectTrailers_Copilot(t *testing.T) {
	msg := "Add feature\n\nCo-authored-by: GitHub Copilot <copilot@github.com>"
	dets := detectTrailers(msg)
	if len(dets) != 1 {
		t.Fatalf("expected 1 detection, got %d", len(dets))
	}
	if dets[0].Tool != ToolCopilot {
		t.Errorf("tool: got %q, want %q", dets[0].Tool, ToolCopilot)
	}
}

func TestDetectTrailers_MixedCase(t *testing.T) {
	msg := "Fix bug\n\nCO-AUTHORED-BY: Claude <noreply@anthropic.com>"
	dets := detectTrailers(msg)
	if len(dets) != 1 {
		t.Fatalf("expected 1 detection, got %d", len(dets))
	}
	if dets[0].Tool != ToolClaudeCode {
		t.Errorf("tool: got %q, want %q", dets[0].Tool, ToolClaudeCode)
	}
}

func TestDetectTrailers_Multiple(t *testing.T) {
	msg := "Fix bug\n\nCo-Authored-By: Claude <noreply@anthropic.com>\nCo-authored-by: GitHub Copilot <copilot@github.com>"
	dets := detectTrailers(msg)
	if len(dets) != 2 {
		t.Fatalf("expected 2 detections, got %d", len(dets))
	}
	tools := make(map[Tool]bool)
	for _, d := range dets {
		tools[d.Tool] = true
	}
	if !tools[ToolClaudeCode] || !tools[ToolCopilot] {
		t.Errorf("expected claude-code and copilot, got %v", tools)
	}
}

func TestDetectTrailers_Aider(t *testing.T) {
	msg := "aider: fix authentication flow"
	dets := detectTrailers(msg)
	if len(dets) != 1 {
		t.Fatalf("expected 1 detection, got %d", len(dets))
	}
	if dets[0].Tool != ToolAider {
		t.Errorf("tool: got %q, want %q", dets[0].Tool, ToolAider)
	}
}

func TestDetectTrailers_AiderGenerated(t *testing.T) {
	msg := "Fix login bug\n\nGenerated by Aider"
	dets := detectTrailers(msg)
	if len(dets) != 1 {
		t.Fatalf("expected 1 detection, got %d", len(dets))
	}
	if dets[0].Tool != ToolAider {
		t.Errorf("tool: got %q, want %q", dets[0].Tool, ToolAider)
	}
}

func TestDetectTrailers_NoTrailers(t *testing.T) {
	msg := "Just a regular commit message\n\nWith some description"
	dets := detectTrailers(msg)
	if len(dets) != 0 {
		t.Errorf("expected 0 detections, got %d: %+v", len(dets), dets)
	}
}

func TestDetectTrailers_DuplicateIgnored(t *testing.T) {
	msg := "Fix\n\nCo-Authored-By: Claude <noreply@anthropic.com>\nCo-authored-by: Claude Opus <noreply@anthropic.com>"
	dets := detectTrailers(msg)
	if len(dets) != 1 {
		t.Fatalf("expected 1 detection (deduped), got %d", len(dets))
	}
}
