package detector

import (
	"strings"
)

// Known AI tool email patterns in Co-Authored-By trailers.
var trailerPatterns = map[string]Tool{
	"noreply@anthropic.com": ToolClaudeCode,
	"copilot@github.com":    ToolCopilot,
	"cursor@cursor.com":     ToolCursor,
}

// detectTrailers parses a commit message and returns detections from
// Co-Authored-By trailers and other AI attribution patterns.
func detectTrailers(commitMsg string) []Detection {
	var detections []Detection
	seen := make(map[Tool]bool)

	for _, line := range strings.Split(commitMsg, "\n") {
		lower := strings.ToLower(strings.TrimSpace(line))

		// Check Co-Authored-By pattern
		if strings.HasPrefix(lower, "co-authored-by:") {
			for pattern, tool := range trailerPatterns {
				if strings.Contains(lower, pattern) && !seen[tool] {
					seen[tool] = true
					detections = append(detections, Detection{
						Tool:       tool,
						Confidence: ConfidenceMedium,
						Method:     MethodCoAuthorTrailer,
					})
				}
			}
		}

		// Check aider patterns
		if (strings.Contains(lower, "generated by aider") ||
			strings.HasPrefix(lower, "aider:")) && !seen[ToolAider] {
			seen[ToolAider] = true
			detections = append(detections, Detection{
				Tool:       ToolAider,
				Confidence: ConfidenceMedium,
				Method:     MethodCoAuthorTrailer,
			})
		}
	}
	return detections
}
